services:
  app:
    image: notaria-web-prod:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: notaria-web-prod
    restart: unless-stopped
    ports:
      - "5173:80"
